		<div id="footer">
			<div>
				<p id="footertext">Site and images by Tyson Haverkort (Copyleft © 2015).  Icons from  <a href="https://icons8.com" target="_blank">Icons8</a></p>
			</div>
			<div id="footer_menu">
				<ul>
					<li class="footer_nav"><a href="./index.html">Home</a></li>
					<li class="footer_nav"><a href="./build_todo.html">To Do</a></li>
					<li class="footer_nav"><a href="./build_done.html">Done</a></li>
					<li class="footer_nav"><a href="./sail_learning.html">Learning</a></li>
					<li class="footer_nav"><a href="./sail_trips.html">Trips</a></li>
					<li class="footer_nav"><a href="./about_boat.html">Boat</a></li>
					<li class="footer_nav"><a href="./about_us.html">About Us</a></li>
					<li class="footer_nav"><a href="./contact.html">Contact</a></li>
				</ul>
			</div>
		</div>